"""Data class.

Store all the necessary data from different functions and classes.

This class provides a neat and understandable way for accessing data generated by different functions within the
package. This class does not function as standalone and is majorly inherited by other classes within the package.

Currently data class is setup for handling arrays only of dense numpy type, but in the future will be optimized for
sparse scipy arrays and for handling huge pytables.
"""


class Data:

    # available solvers in pysolv
    SOLVERS = ['jacobi', 'gaussseidel', 'sor', 'ssor']

    # general solver settings (can be over-ridden by user)
    ITERMAX = 3000
    TOL = 1e-6

    # attributes acquired from other classes by the Data class. Declared as private and for internal use only by the
    # Data class
    __acquired_attrs = []

    def __init__(self):
        """Initialize the class that inherits Data class with all the attributes of the Data class
        """

        self._get_attr()

    @staticmethod
    def add_data(name, data):
        """Add any required data to the data class to be shared with other functions/classes

        Parameters:
            name (string): name with which the data can be called
            data (dtype): data to be stored
        """

        setattr(Data, name, data)
        Data.__acquired_attrs.append(name)

    def _get_attr(self):
        """Pass the __dict__ of the Data class to any child class of Data class
        """

        for name, data in Data.__dict__.items():
            try:
                setattr(self, name, data)
            except (TypeError, AttributeError):
                continue

    @staticmethod
    def __reset_data():
        """Flush all the attributes from the Data class. This method is intended to be a private static method. Call
           to this function from outside classes is not recommended.
        """

        for attr in Data.__acquired_attrs:
            try:
                delattr(Data, attr)
            except (TypeError, AttributeError):
                continue
